helloisaac: helloisaac.cpp
	g++ helloisaac.cpp -o hidiho.exec

quad: quadratic.cpp
	g++ quadratic.cpp -o quadratic.exec

pi_finite: pi_finite.cpp
	g++ pi_finite.cpp -o pi_finite.exec

pi_monte: pi_monte.cpp
	g++ pi_monte.cpp -o pi_monte.exec
