normalize: normalize_vec.cpp
	g++ normalize_vec.cpp -fopenmp -o normalize.exec

dot_prod: dot_prod.cpp
	g++ dot_prod.cpp -fopenmp -o dot_prod.exec

dot_test: dot_test.cpp
	g++ dot_test.cpp -fopenmp -o dot_test.exec

pi_monte: pi_monte.cpp
	g++ pi_monte.cpp -fopenmp -o pi_monte.exec
